# Generated by Django 5.1.2 on 2025-08-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('ingredient', 'Ingredient Type'), ('flavor', 'Flavor Type'), ('style', 'Preparation Style'), ('packaging', 'Packaging Type')], default='ingredient', max_length=50),
        ),
    ]
