# Generated by Django 5.1.2 on 2025-07-20 11:45

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_identification_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=255)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=255)),
                ('business_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('business_email', models.EmailField(blank=True, max_length=255)),
                ('business_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('business_city', models.CharField(blank=True, max_length=100)),
                ('business_street', models.CharField(blank=True, max_length=255)),
                ('business_postal_code', models.CharField(blank=True, max_length=20)),
                ('shipping_policy', models.TextField(blank=True)),
                ('return_policy', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
