# Generated by Django X.Y.Z on YYYY-MM-DD HH:MM

from django.db import migrations
from django.utils.text import slugify

def populate_email_field(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')
    for user in CustomUser.objects.filter(email__isnull=True):
        # Generate a unique temporary email
        # This is a placeholder; you might need a more sophisticated way to ensure uniqueness
        # For example, combine username, id, or a timestamp
        base_email = f'temp_{slugify(user.username or user.id)}'
        email = f'{base_email}@example.com'
        count = 1
        while CustomUser.objects.filter(email=email).exists():
            email = f'{base_email}_{count}@example.com'
            count += 1
        user.email = email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sellerprofile'), 
    ]

    operations = [
        migrations.RunPython(populate_email_field, reverse_code=migrations.RunPython.noop),
    ]

