# Generated by Django 5.1.2 on 2025-09-12 12:01

import user.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", user.models.CustomUserManager()),
            ],
        ),
    ]
